// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBON-mL5EMBbbn3JT5R_TIUiETNMTK4fwU',
    appId: '1:12296658033:web:f5d079439ab7f262a00fd0',
    messagingSenderId: '12296658033',
    projectId: 'diary-app-1c552',
    authDomain: 'diary-app-1c552.firebaseapp.com',
    storageBucket: 'diary-app-1c552.firebasestorage.app',
    measurementId: 'G-0D0MD83SR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAK1A197M4254kKYTVsl7SLfF_idlKZfE',
    appId: '1:12296658033:android:a6b3c715caebb87aa00fd0',
    messagingSenderId: '12296658033',
    projectId: 'diary-app-1c552',
    storageBucket: 'diary-app-1c552.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCxipjTE7pwpIRVhYkPOI5ZrGCJkDYrFE',
    appId: '1:12296658033:ios:40f4728283daa95ca00fd0',
    messagingSenderId: '12296658033',
    projectId: 'diary-app-1c552',
    storageBucket: 'diary-app-1c552.firebasestorage.app',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCxipjTE7pwpIRVhYkPOI5ZrGCJkDYrFE',
    appId: '1:12296658033:ios:40f4728283daa95ca00fd0',
    messagingSenderId: '12296658033',
    projectId: 'diary-app-1c552',
    storageBucket: 'diary-app-1c552.firebasestorage.app',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBON-mL5EMBbbn3JT5R_TIUiETNMTK4fwU',
    appId: '1:12296658033:web:2b18340b569f1fd6a00fd0',
    messagingSenderId: '12296658033',
    projectId: 'diary-app-1c552',
    authDomain: 'diary-app-1c552.firebaseapp.com',
    storageBucket: 'diary-app-1c552.firebasestorage.app',
    measurementId: 'G-1XVRZRQRBJ',
  );
}
